"use client";

import { LightbulbIcon, XIcon } from "@/components/ui/icons";

export type HintState = { status: "loading" } | { status: "done"; text: string } | { status: "error"; message: string };

/** An AI hint from Snowflake Cortex: a nudge about the current code, never the fix. */
export default function HintCard({ hint, onClose }: { hint: HintState; onClose: () => void }) {
  return (
    <div className="mx-4 mt-4 rounded-lg border border-accent/30 bg-accent/5 p-3" role="status" aria-live="polite">
      <div className="flex items-start gap-2.5">
        <LightbulbIcon className="mt-0.5 size-4 shrink-0 text-accent" />
        <div className="min-w-0 flex-1 text-sm">
          <p className="text-xs font-semibold text-accent">Hint</p>
          {hint.status === "loading" ? (
            <div className="mt-1.5 space-y-1.5" aria-label="Thinking">
              <span className="block h-2.5 w-11/12 animate-pulse rounded bg-accent/15" />
              <span className="block h-2.5 w-3/4 animate-pulse rounded bg-accent/15" />
            </div>
          ) : hint.status === "error" ? (
            <p className="mt-1 text-red-300">{hint.message}</p>
          ) : (
            <p className="mt-1 whitespace-pre-wrap leading-relaxed text-zinc-200">{hint.text}</p>
          )}
          <p className="mt-2 text-[10px] text-zinc-500">Generated by Snowflake Cortex · nudges you toward the bug, never the fix</p>
        </div>
        <button type="button" onClick={onClose} aria-label="Dismiss hint" className="text-zinc-500 hover:text-zinc-200">
          <XIcon className="size-3.5" />
        </button>
      </div>
    </div>
  );
}
